### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by sherfruit** [zhoou/vue-cli-multipage-bootstrap#1]
您好 请问有博客详细的说明吗？还有在引入其它UI框架的时候，是像你一样import css文件就行了？ 是否仍需要npm i?

**Comment by zhoou** [comment]
- 本项目是我在学习vue2.0时做的，目前是学到哪完善到哪，暂时还没整理文档说明。

- 至于引入其他UI框架的话，本项目中是用的bootstrap，在根目录import css和js，用webpack打包好就行，你也可以直接用npm安装然后再引用

- 由于项目中用webpack打包，需要npm install
