### ISSUE TITLE
highlight js question

### ISSUE THREAD

**Issue by subdesign** [zhoou/vue-cli-multipage-bootstrap#2]
Hey, could you please explain, how do you solve that when the router loads a component, the source code is highlighted with highlight.js ? I see some code in webpack config, but not clear how it makes in the js code.. 
I tried this package, https://github.com/metachris/vue-highlightjs but it works only in the main.js, not in components.
thanks

**Comment by subdesign** [comment]
I find it in the code deep inside, and it works, thanks for the superb learning repo!

**Comment by zhoou** [comment]
I am glad this demo can help you !
